#ifndef RIVALINTERFACE_GLOBAL_H
#define RIVALINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RIVALINTERFACE_LIBRARY)
#  define RIVALINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define RIVALINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // RIVALINTERFACE_GLOBAL_H
