name: main
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Build
      # You may pin to the exact commit or the version.
      # uses: jurplel/install-qt-action@b3ea5275e37b734d027040e2c7fe7a10ea2ef946
      - uses: jurplel/install-qt-action@v3.3.0
